In [2]:
# MATRIZ PSEUDO INVERSA DE MOORE PENROSE

import numpy as np

np.set_printoptions(suppress = True) # Esto hace que no nos muestre los números muy cercanos a 0

In [3]:
# A_pseudo = V (obtendido como de U*D*V) * D_pseudo * U_transpuesta

A = np.array([[2, 3], [5, 7], [11, 13]])
print(A)

[[ 2  3]
 [ 5  7]
 [11 13]]


In [4]:
U, D, V = np.linalg.svd(A)
print("U")
print('')
print(U)
print('')
print("D")
print('')
print(D)
print('')
print("V")
print('')
print(V)

U

[[-0.18499741 -0.47276624 -0.86154979]
 [-0.44249308 -0.74271297  0.50257071]
 [-0.87748267  0.4742041  -0.07179582]]

D

[19.40321383  0.71783924]

V

[[-0.63055377 -0.77614557]
 [ 0.77614557 -0.63055377]]


In [5]:
# ESTE ES EL MÉTODO LARGO PARA CALCULAR LA PSEUDO INVERSA

D_pse = np.zeros((A.shape[0], A.shape[1])).T
print(D_pse)

[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
print('Valores a remplazar en D_pse')
print(D_pse[:D.shape[0], :D.shape[0]])

Valores a remplazar en D_pse
[[0. 0.]
 [0. 0.]]


In [7]:
print('Valores que pondremos en en D_pse')
print(np.linalg.inv(np.diag(D)))

Valores que pondremos en en D_pse
[[0.05153785 0.        ]
 [0.         1.39306957]]


In [8]:
print('D_pse')
D_pse[:D.shape[0], :D.shape[0]] = np.linalg.inv(np.diag(D)) 
print(D_pse)

D_pse
[[0.05153785 0.         0.        ]
 [0.         1.39306957 0.        ]]


In [9]:
A_pse = V.T.dot(D_pse).dot(U.T)
print(A_pse)

[[-0.50515464 -0.78865979  0.54123711]
 [ 0.42268041  0.67010309 -0.3814433 ]]


In [10]:
# ESTE ES EL MÉTODO DIRECTO DE NUMPY

A_pse_calc = np.linalg.pinv(A)
print(A_pse_calc)

[[-0.50515464 -0.78865979  0.54123711]
 [ 0.42268041  0.67010309 -0.3814433 ]]


In [11]:
# VEMOS QUE A*A_pse es casi la identidad A* A_pse = Id Pero no es lo mismo

print(A_pse.dot(A))

[[ 1. -0.]
 [ 0.  1.]]


In [12]:
# Lo verificamos 

np.set_printoptions(suppress = False)

In [13]:
print(A_pse.dot(A))

[[ 1.00000000e+00 -1.77635684e-15]
 [ 4.44089210e-16  1.00000000e+00]]


In [14]:
# A_pse no es lo mismo que A^-1, la inversa común se puede multiplicar a izquierda o derecha, en la pseudoinversa no pasa, lo verificamos

# A_pse no son conmutativas

print(A.dot(A_pse)) # No da nada parecido a la identidad 

[[ 0.25773196  0.43298969 -0.06185567]
 [ 0.43298969  0.74742268  0.03608247]
 [-0.06185567  0.03608247  0.99484536]]


In [15]:
A_pse_2 = np.linalg.inv(A.T.dot(A)).dot(A.T)  # OTRO TIPO DE PSEUDO INVERSA PERO NUMPY USA LA QUE VIMOS ANTERIORMENTE 
print(A_pse_2)

[[-0.50515464 -0.78865979  0.54123711]
 [ 0.42268041  0.67010309 -0.3814433 ]]


In [16]:
B = np.array([[1, 2], [3, 4], [5, 6]])
print(B)

[[1 2]
 [3 4]
 [5 6]]


In [17]:
B_pse = np.linalg.pinv(B)
print(B_pse)

[[-1.33333333 -0.33333333  0.66666667]
 [ 1.08333333  0.33333333 -0.41666667]]
