In [1]:
%matplotlib inline

import numpy as np

In [3]:
A = np.array ([[1,2,3], [3,4,5]])
print(A)

[[1 2 3]
 [3 4 5]]


In [15]:
# Nos permite calcular los valores propios

U,D,V = np.linalg.svd(A)

In [11]:
print(U)

[[-0.46410668 -0.88577931]
 [-0.88577931  0.46410668]]


In [12]:
print(D)

[7.97638869 0.61418515]


In [13]:
print(np.diag(D))

[[7.97638869 0.        ]
 [0.         0.61418515]]


In [14]:
print(V)

[[-0.39133557 -0.5605708  -0.72980603]
 [ 0.8247362   0.13817999 -0.54837623]
 [ 0.40824829 -0.81649658  0.40824829]]


In [22]:
# Para reconstruir la matriz A es A = U * D * V donde D es el puente para cambio de dimensión
# Agrego columna de 0's a D para que sea una matriz 2x3 y pueda multiplicarse con V que es 3x3, queda la multiplicación 2x2, 2x3, 3x3 

C = np.array([[D[0],0,0],[0,D[1],0]])

X = U.dot(C).dot(V)

In [23]:
print(X)

[[1. 2. 3.]
 [3. 4. 5.]]
